"use client";

import { useEffect, useState } from "react";
import { LoaderCircle, Search, Users } from "lucide-react";

type Customer = { phone: string; name: string; email: string | null; userId: string | null; orderCount: number; lifetimeValue: number; latestOrderAt: string };
const money = (value: number) => new Intl.NumberFormat("vi-VN").format(value);

export default function AdminCustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/admin/customers?search=${encodeURIComponent(search)}`); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Không thể tải khách hàng."); else { setCustomers(result.customers || []); setError(""); } setLoading(false); }
  // The protected customer search intentionally hydrates state after the initial render.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, []);
  return <main className="min-h-screen bg-background px-5 py-6 sm:px-8"><div className="mx-auto max-w-7xl"><header className="mb-6"><p className="font-display text-2xl">CÁ&apos;S HOA</p><p className="mt-1 text-sm text-muted-foreground">Tổng hợp khách hàng từ đơn guest và tài khoản</p></header><section className="py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-primary"><Users size={14} /> Customer management</p><h1 className="mt-2 font-display text-4xl">Khách hàng</h1></div><p className="text-sm text-muted-foreground">{customers.length} khách đã tổng hợp</p></div><div className="mt-7 flex max-w-2xl gap-3"><label className="relative block flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") load(); }} className="h-12 w-full rounded-full border border-border bg-surface pl-11 pr-4" placeholder="Tìm tên, số điện thoại hoặc email" /></label><button onClick={load} className="h-12 rounded-full bg-primary px-5 font-bold text-white">Tìm</button></div>{error && <p role="alert" className="mt-5 rounded-xl bg-[#fae8e4] p-4 text-sm text-danger">{error}</p>}{loading ? <div className="flex justify-center py-16"><LoaderCircle className="animate-spin text-primary" /></div> : <div className="mt-8 overflow-x-auto rounded-[24px] border border-border bg-surface"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-border bg-background text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-4">Khách hàng</th><th className="px-5 py-4">Số điện thoại</th><th className="px-5 py-4">Số đơn</th><th className="px-5 py-4">Tổng giá trị</th><th className="px-5 py-4">Đơn gần nhất</th></tr></thead><tbody>{customers.map((customer) => <tr key={customer.phone} className="border-b border-border last:border-0"><td className="px-5 py-5"><p className="font-semibold">{customer.name}</p><p className="text-xs text-muted-foreground">{customer.userId ? "Customer account" : "Guest customer"}</p></td><td className="px-5 py-5">{customer.phone}</td><td className="px-5 py-5">{customer.orderCount}</td><td className="px-5 py-5 font-bold text-primary">{money(customer.lifetimeValue)}đ</td><td className="px-5 py-5 text-muted-foreground">{new Date(customer.latestOrderAt).toLocaleString("vi-VN")}</td></tr>)}</tbody></table>{customers.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">Chưa có khách phù hợp.</p>}</div>}</section></div></main>;
}
