"use client";

import { useEffect, useState } from "react";
import { History, LoaderCircle } from "lucide-react";
import AdminNav from "../_components/AdminNav";

type Transaction = { id: string; transaction_type: string; quantity_change: number; quantity_before: number | null; quantity_after: number | null; reason: string; note: string; order_id: string | null; created_at: string; inventory_items: { name: string; unit: string } | null };
const labels: Record<string, string> = { import: "Nhập kho", damaged: "Hư hỏng", adjustment: "Điều chỉnh", reserve: "Giữ cho đơn", release: "Hoàn giữ", consume: "Đã dùng", order: "Đơn hàng" };

export default function InventoryHistoryPage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [type, setType] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/admin/inventory/transactions?limit=200${type ? `&type=${encodeURIComponent(type)}` : ""}`); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Không thể tải lịch sử kho."); else { setTransactions(result.transactions || []); setError(""); } setLoading(false); }
  // The protected history fetch intentionally hydrates after mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [type]);
  return <main className="min-h-screen bg-background px-5 py-6 sm:px-8"><div className="mx-auto max-w-7xl"><header className="mb-6"><p className="font-display text-2xl">CÁ&apos;S HOA</p><p className="mt-1 text-sm text-muted-foreground">Audit mọi biến động nguyên liệu</p></header><AdminNav /><section className="py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-primary"><History size={14} /> Inventory audit</p><h1 className="mt-2 font-display text-4xl">Lịch sử kho</h1></div><select value={type} onChange={(event) => setType(event.target.value)} className="h-11 rounded-full border border-border bg-surface px-4 text-sm"><option value="">Tất cả giao dịch</option><option value="import">Nhập kho</option><option value="damaged">Hư hỏng</option><option value="adjustment">Điều chỉnh</option><option value="reserve">Giữ cho đơn</option><option value="release">Hoàn giữ</option><option value="consume">Đã dùng</option></select></div>{error && <p role="alert" className="mt-5 rounded-xl bg-[#fae8e4] p-4 text-sm text-danger">{error}</p>}{loading ? <div className="flex justify-center py-16"><LoaderCircle className="animate-spin text-primary" /></div> : <div className="mt-8 overflow-x-auto rounded-[24px] border border-border bg-surface"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-border bg-background text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-4">Thời gian</th><th className="px-5 py-4">Nguyên liệu</th><th className="px-5 py-4">Loại</th><th className="px-5 py-4">Biến động</th><th className="px-5 py-4">Trước → sau</th><th className="px-5 py-4">Lý do</th></tr></thead><tbody>{transactions.map((item) => <tr key={item.id} className="border-b border-border last:border-0"><td className="px-5 py-4 text-muted-foreground">{new Date(item.created_at).toLocaleString("vi-VN")}</td><td className="px-5 py-4 font-semibold">{item.inventory_items?.name || "Không rõ"} <span className="text-xs font-normal text-muted-foreground">({item.inventory_items?.unit || ""})</span></td><td className="px-5 py-4">{labels[item.transaction_type] || item.transaction_type}</td><td className={`px-5 py-4 font-bold ${item.quantity_change < 0 ? "text-danger" : "text-primary"}`}>{item.quantity_change > 0 ? "+" : ""}{item.quantity_change}</td><td className="px-5 py-4">{item.quantity_before ?? "—"} → {item.quantity_after ?? "—"}</td><td className="max-w-[280px] px-5 py-4 text-muted-foreground">{item.reason}{item.note ? ` · ${item.note}` : ""}</td></tr>)}</tbody></table>{transactions.length === 0 && <p className="p-8 text-center text-sm text-muted-foreground">Chưa có biến động phù hợp.</p>}</div>}</section></div></main>;
}
