"use client";

import { useEffect, useState } from "react";
import { CalendarDays, LoaderCircle, Truck } from "lucide-react";
import AdminNav from "../_components/AdminNav";

type Order = { id: string; order_code: string; recipient_name: string; recipient_phone: string; is_pickup: boolean; delivery_address: string | null; delivery_date: string | null; delivery_time: string | null; delivery_status: string; status: string; shipping_vnd: number; shipping_fee_confirmed: boolean; carrier_name: string | null; shipper_name: string | null };
const labels: Record<string, string> = { pending_confirmation: "Chờ xác nhận", confirmed: "Đã xác nhận", preparing: "Đang chuẩn bị", ready: "Sẵn sàng", delivering: "Đang giao", completed: "Hoàn thành", cancelled: "Đã hủy" };
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(new Date()); }

export default function AdminDeliveryPage() {
  const [date, setDate] = useState(today()); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); const response = await fetch(`/api/ops/orders?deliveryDate=${date}&pageSize=100`); const result = await response.json().catch(() => ({})); if (!response.ok) setError(result.error || "Không thể tải lịch giao."); else { setOrders(result.orders || []); setError(""); } setLoading(false); }
  // Date-scoped protected data is intentionally loaded after mount.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [date]);
  return <main className="min-h-screen bg-background px-5 py-6 sm:px-8"><div className="mx-auto max-w-7xl"><header className="mb-6"><p className="font-display text-2xl">CÁ&apos;S HOA</p><p className="mt-1 text-sm text-muted-foreground">Lịch giao hàng và đơn tự tới lấy</p></header><AdminNav /><section className="py-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-primary"><Truck size={14} /> Delivery operations</p><h1 className="mt-2 font-display text-4xl">Giao hàng</h1></div><label className="flex items-center gap-2 rounded-full border border-border bg-surface px-4"><CalendarDays size={17} className="text-primary" /><input value={date} onChange={(event) => setDate(event.target.value)} type="date" className="h-11 bg-transparent text-sm" /></label></div>{error && <p role="alert" className="mt-5 rounded-xl bg-[#fae8e4] p-4 text-sm text-danger">{error}</p>}{loading ? <div className="flex justify-center py-16"><LoaderCircle className="animate-spin text-primary" /></div> : <div className="mt-8 grid gap-4 lg:grid-cols-2">{orders.map((order) => <article key={order.id} className="rounded-[24px] border border-border bg-surface p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{order.order_code}</p><p className="mt-1 text-sm">{order.recipient_name} · {order.recipient_phone}</p></div><span className="rounded-full bg-[#e4ecdf] px-3 py-1 text-xs font-bold text-primary">{labels[order.status] || order.status}</span></div><p className="mt-4 text-sm font-semibold">{order.is_pickup ? "Tự tới lấy tại shop" : order.delivery_address || "Chưa có địa chỉ"}</p><p className="mt-1 text-sm text-muted-foreground">{order.delivery_time || "Chưa có khung giờ"} · {order.delivery_status}</p><div className="mt-4 flex items-center justify-between border-t border-border pt-4 text-sm"><span>{order.shipping_fee_confirmed || order.is_pickup ? `Phí: ${new Intl.NumberFormat("vi-VN").format(order.shipping_vnd)}đ` : "Chưa chốt phí ship"}</span><a href="/admin/orders" className="rounded-full border border-border px-4 py-2 font-bold">Mở đơn</a></div></article>)}{orders.length === 0 && <div className="rounded-[24px] border border-border bg-surface p-8 text-center text-sm text-muted-foreground lg:col-span-2">Không có đơn giao/nhận trong ngày này.</div>}</div>}</section></div></main>;
}
